apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::620455725858:user/TerraformUser
      username: TerraformUser
      groups:
        - system:masters
    - userarn: arn:aws:iam::620455725858:user/admin
      username: admin
      groups:
        - system:masters
