---
# SecretStore: AWS SSM Parameter Store 연결
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-ssm-store
  namespace: web
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: muze-web-sa  # IRSA ServiceAccount

---
# ExternalSecret: SSM 파라미터를 K8s Secret으로 동기화
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: muze-app-secrets
  namespace: web
spec:
  refreshInterval: 1h  # 1시간마다 SSM에서 최신 값 가져옴
  secretStoreRef:
    name: aws-ssm-store
    kind: SecretStore
  target:
    name: muze-app-secrets  # 생성될 K8s Secret 이름
    creationPolicy: Owner
  data:
  # Django
  - secretKey: SECRET_KEY
    remoteRef:
      key: /muze/prod/SECRET_KEY
  # Database
  - secretKey: DB_NAME
    remoteRef:
      key: /muze/prod/DB_NAME
  - secretKey: DB_USER
    remoteRef:
      key: /muze/prod/DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /muze/prod/DB_PASSWORD
  - secretKey: DB_PORT
    remoteRef:
      key: /muze/prod/DB_PORT
  # Redis
  - secretKey: REDIS_PORT
    remoteRef:
      key: /muze/prod/REDIS_PORT
  - secretKey: REDIS_DB
    remoteRef:
      key: /muze/prod/REDIS_DB
  - secretKey: REDIS_PASS
    remoteRef:
      key: /muze/prod/REDIS_PASS
